name: "Powerwall3 to MQTT"
description: "A bridge between a Tesla Powerwall3 and MQTT"
version: "0.0.1"
slug: "powerwall3mqtt"
init: false
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
options:
  tedapi_report_vitals: false
  tedapi_poll_interval: 30
  mqtt_base_topic: "homeassistant"
schema:
  tedapi_password: str
  tedapi_report_vitals: bool
  tedapi_poll_interval: int(5,300)
  mqtt_server: "str?"
  mqtt_port: "int?"
  mqtt_ca: "str?"
  mqtt_key: "str?"
  mqtt_cert: "str?"
  mqtt_verify_tls: bool
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_base_topic: str
